"""Add new column

Revision ID: 85bcb8c82085
Revises: 
Create Date: 2025-01-26 00:52:44.726546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bcb8c82085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('vx', sa.Float(), nullable=False),
    sa.Column('vy', sa.Float(), nullable=False),
    sa.Column('ax', sa.Float(), nullable=False),
    sa.Column('ay', sa.Float(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('elasitcity', sa.Float(), nullable=False),
    sa.Column('friction', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable')
    # ### end Alembic commands ###
