"""Add new column

Revision ID: f74d8742c965
Revises: 85bcb8c82085
Create Date: 2025-01-26 00:57:11.494600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74d8742c965'
down_revision = '85bcb8c82085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elasticity', sa.Float(), nullable=False))
        batch_op.drop_column('elasitcity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elasitcity', sa.FLOAT(), nullable=False))
        batch_op.drop_column('elasticity')

    # ### end Alembic commands ###
